# -*- coding: utf-8 -*-

from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import ugettext_lazy as _

from cms.models import CMSPlugin
from cms.models.fields import PageField

from .utils import get_additional_styles, get_additional_names

# Default Font-Awesome icon names
ICON_NAMES = [('fas-icon-adn', _("Adn")),
              ('fas-icon-ajust', _("Ajust")),
              ('fas-icon-align-center', _("Align Center")),
              ('fas-icon-align-justify', _("Align Justify")),
              ('fas-icon-align-left', _("Align Left")),
              ('fas-icon-align-right', _("Align Right")),
              ('fas-icon-ambulance', _("Ambulance")),
              ('fas-icon-anchor', _("Anchor")),
              ('fas-icon-android', _("Android")),
              ('fas-icon-angle-circled-down', _("Angle Circled Down")),
              ('fas-icon-angle-circled-left', _("Angle Circled Left")),
              ('fas-icon-angle-circled-right', _("Angle Circled Right")),
              ('fas-icon-angle-circled-up', _("Angle Circled Up")),
              ('fas-icon-angle-double-down', _("Angle Double Down")),
              ('fas-icon-angle-double-left', _("Angle Double Left")),
              ('fas-icon-angle-double-right', _("Angle Double Right")),
              ('fas-icon-angle-double-up', _("Angle Double Up")),
              ('fas-icon-angle-down', _("Angle Down")),
              ('fas-icon-angle-left', _("Angle Left")),
              ('fas-icon-angle-right', _("Angle Right")),
              ('fas-icon-angle-up', _("Angle Up")),
              ('fas-icon-apple', _("Apple")),
              ('fas-icon-arrows-cw', _("Arrows Cw")),
              ('fas-icon-asterisk', _("Asterisk")),
              ('fas-icon-attach', _("Attach")),
              ('fas-icon-attention', _("Attention")),
              ('fas-icon-attention-alt', _("Attention Alt")),
              ('fas-icon-attention-circled', _("Attention Circled")),
              ('fas-icon-award', _("Award")),
              ('fas-icon-barcode', _("Barcode")),
              ('fas-icon-basket', _("Basket")),
              ('fas-icon-beaker', _("Beaker")),
              ('fas-icon-beer', _("Beer")),
              ('fas-icon-bell', _("Bell")),
              ('fas-icon-bell-alt', _("Bell Alt")),
              ('fas-icon-bitbucket', _("Bitbucket")),
              ('fas-icon-bitbucket-squared', _("Bitbucket Squared")),
              ('fas-icon-bitcoin', _("Bitcoin")),
              ('fas-icon-blank', _("Blank")),
              ('fas-icon-block', _("Block")),
              ('fas-icon-bold', _("Bold")),
              ('fas-icon-book', _("Book")),
              ('fas-icon-bookmark', _("Bookmark")),
              ('fas-icon-bookmark-empty', _("Bookmark Empty")),
              ('fas-icon-box', _("Box")),
              ('fas-icon-briefcase', _("Briefcase")),
              ('fas-icon-bug', _("Bug")),
              ('fas-icon-building', _("Building")),
              ('fas-icon-bullseye', _("Bullseye")),
              ('fas-icon-calendar', _("Calendar")),
              ('fas-icon-calendar-empty', _("Calendar Empty")),
              ('fas-icon-camera', _("Camera")),
              ('fas-icon-camera-alt', _("Camera Alt")),
              ('fas-icon-cancel', _("Cancel")),
              ('fas-icon-cancel-circled', _("Cancel Circled")),
              ('fas-icon-cancel-circled2', _("Cancel Circled2")),
              ('fas-icon-ccw', _("Ccw")),
              ('fas-icon-certificate', _("Certificate")),
              ('fas-icon-chart-bar', _("Chart Bar")),
              ('fas-icon-chat', _("Chat")),
              ('fas-icon-chat-empty', _("Chat Empty")),
              ('fas-icon-check', _("Check")),
              ('fas-icon-check-empty', _("Check Empty")),
              ('fas-icon-circle', _("Circle")),
              ('fas-icon-circle-empty', _("Circle Empty")),
              ('fas-icon-clock', _("Clock")),
              ('fas-icon-cloud', _("Cloud")),
              ('fas-icon-code', _("Code")),
              ('fas-icon-coffee', _("Coffee")),
              ('fas-icon-cog', _("Cog")),
              ('fas-icon-cog-alt', _("Cog Alt")),
              ('fas-icon-collapse', _("Collapse")),
              ('fas-icon-collapse-left', _("Collapse Left")),
              ('fas-icon-columns', _("Columns")),
              ('fas-icon-comment', _("Comment")),
              ('fas-icon-comment-empty', _("Comment Empty")),
              ('fas-icon-compass', _("Compass")),
              ('fas-icon-credit-card', _("Credit Card")),
              ('fas-icon-crop', _("Crop")),
              ('fas-icon-css3', _("Css3")),
              ('fas-icon-cw', _("Cw")),
              ('fas-icon-desktop', _("Desktop")),
              ('fas-icon-direction', _("Direction")),
              ('fas-icon-doc', _("Doc")),
              ('fas-icon-doc-inv', _("Doc Inv")),
              ('fas-icon-doc-text', _("Doc Text")),
              ('fas-icon-doc-text-inv', _("Doc Text Inv")),
              ('fas-icon-docs', _("Docs")),
              ('fas-icon-dollar', _("Dollar")),
              ('fas-icon-dot-circled', _("Dot Circled")),
              ('fas-icon-down', _("Down")),
              ('fas-icon-down-big', _("Down Big")),
              ('fas-icon-down-circled', _("Down Circled")),
              ('fas-icon-down-circled2', _("Down Circled2")),
              ('fas-icon-down-dir', _("Down Dir")),
              ('fas-icon-down-hand', _("Down Hand")),
              ('fas-icon-down-open', _("Down Open")),
              ('fas-icon-download', _("Download")),
              ('fas-icon-download-cloud', _("Download Cloud")),
              ('fas-icon-dribbble', _("Dribbble")),
              ('fas-icon-dropbox', _("Dropbox")),
              ('fas-icon-edit', _("Edit")),
              ('fas-icon-eject', _("Eject")),
              ('fas-icon-ellipsis', _("Ellipsis")),
              ('fas-icon-ellipsis-vert', _("Ellipsis Vert")),
              ('fas-icon-eraser', _("Eraser")),
              ('fas-icon-euro', _("Euro")),
              ('fas-icon-exchange', _("Exchange")),
              ('fas-icon-expand', _("Expand")),
              ('fas-icon-expand-right', _("Expand Right")),
              ('fas-icon-export', _("Export")),
              ('fas-icon-export-alt', _("Export Alt")),
              ('fas-icon-extinguisher', _("Extinguisher")),
              ('fas-icon-eye', _("Eye")),
              ('fas-icon-eye-off', _("Eye Off")),
              ('fas-icon-facebook', _("Facebook")),
              ('fas-icon-facebook-squared', _("Facebook Squared")),
              ('fas-icon-fast-bw', _("Fast Bw")),
              ('fas-icon-fast-fw', _("Fast Fw")),
              ('fas-icon-female', _("Female")),
              ('fas-icon-fighter-jet', _("Fighter Jet")),
              ('fas-icon-filter', _("Filter")),
              ('fas-icon-fire', _("Fire")),
              ('fas-icon-flag', _("Flag")),
              ('fas-icon-flag-checkered', _("Flag Checkered")),
              ('fas-icon-flag-empty', _("Flag Empty")),
              ('fas-icon-flash', _("Flash")),
              ('fas-icon-flickr', _("Flickr")),
              ('fas-icon-flight', _("Flight")),
              ('fas-icon-floppy', _("Floppy")),
              ('fas-icon-folder', _("Folder")),
              ('fas-icon-folder-empty', _("Folder Empty")),
              ('fas-icon-folder-open', _("Folder Open")),
              ('fas-icon-folder-open-empty', _("Folder Open Empty")),
              ('fas-icon-font', _("Font")),
              ('fas-icon-food', _("Food")),
              ('fas-icon-fork', _("Fork")),
              ('fas-icon-forward', _("Forward")),
              ('fas-icon-foursquare', _("Foursquare")),
              ('fas-icon-frown', _("Frown")),
              ('fas-icon-gamepad', _("Gamepad")),
              ('fas-icon-gauge', _("Gauge")),
              ('fas-icon-gift', _("Gift")),
              ('fas-icon-github', _("Github")),
              ('fas-icon-github-circled', _("Github Circled")),
              ('fas-icon-github-squared', _("Github Squared")),
              ('fas-icon-gittip', _("Gittip")),
              ('fas-icon-glass', _("Glass")),
              ('fas-icon-globe', _("Globe")),
              ('fas-icon-gplus', _("Gplus")),
              ('fas-icon-gplus-squared', _("Gplus Squared")),
              ('fas-icon-h-sigh', _("H Sigh")),
              ('fas-icon-hammer', _("Hammer")),
              ('fas-icon-hdd', _("Hdd")),
              ('fas-icon-headphones', _("Headphones")),
              ('fas-icon-heart', _("Heart")),
              ('fas-icon-heart-empty', _("Heart Empty")),
              ('fas-icon-help', _("Help")),
              ('fas-icon-help-circled', _("Help Circled")),
              ('fas-icon-home', _("Home")),
              ('fas-icon-hospital', _("Hospital")),
              ('fas-icon-html5', _("Html5")),
              ('fas-icon-inbox', _("Inbox")),
              ('fas-icon-indent-left', _("Indent Left")),
              ('fas-icon-indent-right', _("Indent Right")),
              ('fas-icon-info', _("Info")),
              ('fas-icon-info-circled', _("Info Circled")),
              ('fas-icon-instagramm', _("Instagramm")),
              ('fas-icon-italic', _("Italic")),
              ('fas-icon-key', _("Key")),
              ('fas-icon-keyboard', _("Keyboard")),
              ('fas-icon-laptop', _("Laptop")),
              ('fas-icon-leaf', _("Leaf")),
              ('fas-icon-left', _("Left")),
              ('fas-icon-left-big', _("Left Big")),
              ('fas-icon-left-circled', _("Left Circled")),
              ('fas-icon-left-circled2', _("Left Circled2")),
              ('fas-icon-left-dir', _("Left Dir")),
              ('fas-icon-left-hand', _("Left Hand")),
              ('fas-icon-left-open', _("Left Open")),
              ('fas-icon-lemon', _("Lemon")),
              ('fas-icon-level-down', _("Level Down")),
              ('fas-icon-level-up', _("Level Up")),
              ('fas-icon-lightbulb', _("Lightbulb")),
              ('fas-icon-link', _("Link")),
              ('fas-icon-link-ext', _("Link Ext")),
              ('fas-icon-link-ext-alt', _("Link Ext Alt")),
              ('fas-icon-linkedin', _("Linkedin")),
              ('fas-icon-linkedin-squared', _("Linkedin Squared")),
              ('fas-icon-linux', _("Linux")),
              ('fas-icon-list', _("List")),
              ('fas-icon-list-alt', _("List Alt")),
              ('fas-icon-list-bullet', _("List Bullet")),
              ('fas-icon-list-numbered', _("List Numbered")),
              ('fas-icon-location', _("Location")),
              ('fas-icon-lock', _("Lock")),
              ('fas-icon-lock-open', _("Lock Open")),
              ('fas-icon-lock-open-alt', _("Lock Open Alt")),
              ('fas-icon-login', _("Login")),
              ('fas-icon-logout', _("Logout")),
              ('fas-icon-magic', _("Magic")),
              ('fas-icon-magnet', _("Magnet")),
              ('fas-icon-mail', _("Mail")),
              ('fas-icon-mail-alt', _("Mail Alt")),
              ('fas-icon-male', _("Male")),
              ('fas-icon-maxcdn', _("Maxcdn")),
              ('fas-icon-medkit', _("Medkit")),
              ('fas-icon-megaphone', _("Megaphone")),
              ('fas-icon-meh', _("Meh")),
              ('fas-icon-menu', _("Menu")),
              ('fas-icon-mic', _("Mic")),
              ('fas-icon-minus', _("Minus")),
              ('fas-icon-minus-circled', _("Minus Circled")),
              ('fas-icon-minus-squared', _("Minus Squared")),
              ('fas-icon-minus-squared-alt', _("Minus Squared Alt")),
              ('fas-icon-mobile', _("Mobile")),
              ('fas-icon-money', _("Money")),
              ('fas-icon-moon', _("Moon")),
              ('fas-icon-move', _("Move")),
              ('fas-icon-music', _("Music")),
              ('fas-icon-mute', _("Mute")),
              ('fas-icon-off', _("Off")),
              ('fas-icon-ok', _("Ok")),
              ('fas-icon-ok-circled', _("Ok Circled")),
              ('fas-icon-ok-circled2', _("Ok Circled2")),
              ('fas-icon-ok-squared', _("Ok Squared")),
              ('fas-icon-pagelines', _("Pagelines")),
              ('fas-icon-paste', _("Paste")),
              ('fas-icon-pause', _("Pause")),
              ('fas-icon-pencil', _("Pencil")),
              ('fas-icon-pencil-squared', _("Pencil Squared")),
              ('fas-icon-phone', _("Phone")),
              ('fas-icon-phone-squared', _("Phone Squared")),
              ('fas-icon-picture', _("Picture")),
              ('fas-icon-pin', _("Pin")),
              ('fas-icon-pinterest-circled', _("Pinterest Circled")),
              ('fas-icon-pinterest-squared', _("Pinterest Squared")),
              ('fas-icon-play', _("Play")),
              ('fas-icon-play-circled', _("Play Circled")),
              ('fas-icon-play-circled2', _("Play Circled2")),
              ('fas-icon-plus', _("Plus")),
              ('fas-icon-plus-circled', _("Plus Circled")),
              ('fas-icon-plus-squared', _("Plus Squared")),
              ('fas-icon-plus-squared-alt', _("Plus Squared Alt")),
              ('fas-icon-pound', _("Pound")),
              ('fas-icon-print', _("Print")),
              ('fas-icon-puzzle', _("Puzzle")),
              ('fas-icon-qrcode', _("Qrcode")),
              ('fas-icon-quote-left', _("Quote Left")),
              ('fas-icon-quote-right', _("Quote Right")),
              ('fas-icon-renren', _("Renren")),
              ('fas-icon-reply', _("Reply")),
              ('fas-icon-reply-all', _("Reply All")),
              ('fas-icon-resize-full', _("Resize Full")),
              ('fas-icon-resize-full-alt', _("Resize Full Alt")),
              ('fas-icon-resize-horizontal', _("Resize Horizontal")),
              ('fas-icon-resize-small', _("Resize Small")),
              ('fas-icon-resize-vertical', _("Resize Vertical")),
              ('fas-icon-retweet', _("Retweet")),
              ('fas-icon-right', _("Right")),
              ('fas-icon-right-big', _("Right Big")),
              ('fas-icon-right-circled', _("Right Circled")),
              ('fas-icon-right-circled2', _("Right Circled2")),
              ('fas-icon-right-dir', _("Right Dir")),
              ('fas-icon-right-hand', _("Right Hand")),
              ('fas-icon-right-open', _("Right Open")),
              ('fas-icon-road', _("Road")),
              ('fas-icon-rocket', _("Rocket")),
              ('fas-icon-rouble', _("Rouble")),
              ('fas-icon-rss', _("Rss")),
              ('fas-icon-rss-squared', _("Rss Squared")),
              ('fas-icon-rupee', _("Rupee")),
              ('fas-icon-scissors', _("Scissors")),
              ('fas-icon-search', _("Search")),
              ('fas-icon-shield', _("Shield")),
              ('fas-icon-shuffle', _("Shuffle")),
              ('fas-icon-signal', _("Signal")),
              ('fas-icon-sitemap', _("Sitemap")),
              ('fas-icon-skype', _("Skype")),
              ('fas-icon-smile', _("Smile")),
              ('fas-icon-sort', _("Sort")),
              ('fas-icon-sort-alt-down', _("Sort Alt Down")),
              ('fas-icon-sort-alt-up', _("Sort Alt Up")),
              ('fas-icon-sort-down', _("Sort Down")),
              ('fas-icon-sort-name-down', _("Sort Name Down")),
              ('fas-icon-sort-name-up', _("Sort Name Up")),
              ('fas-icon-sort-number-down', _("Sort Number Down")),
              ('fas-icon-sort-number-up', _("Sort Number Up")),
              ('fas-icon-sort-up', _("Sort Up")),
              ('fas-icon-spinner', _("Spinner")),
              ('fas-icon-stackexchange', _("Stackexchange")),
              ('fas-icon-stackoverflow', _("Stackoverflow")),
              ('fas-icon-star', _("Star")),
              ('fas-icon-star-empty', _("Star Empty")),
              ('fas-icon-star-half', _("Star Half")),
              ('fas-icon-star-half-alt', _("Star Half Alt")),
              ('fas-icon-stethoscope', _("Stethoscope")),
              ('fas-icon-stop', _("Stop")),
              ('fas-icon-strike', _("Strike")),
              ('fas-icon-subscript', _("Subscript")),
              ('fas-icon-suitcase', _("Suitcase")),
              ('fas-icon-sun', _("Sun")),
              ('fas-icon-superscript', _("Superscript")),
              ('fas-icon-table', _("Table")),
              ('fas-icon-tablet', _("Tablet")),
              ('fas-icon-tag', _("Tag")),
              ('fas-icon-tags', _("Tags")),
              ('fas-icon-target', _("Target")),
              ('fas-icon-tasks', _("Tasks")),
              ('fas-icon-terminal', _("Terminal")),
              ('fas-icon-text-height', _("Text Height")),
              ('fas-icon-text-width', _("Text Width")),
              ('fas-icon-th', _("Th")),
              ('fas-icon-th-large', _("Th Large")),
              ('fas-icon-th-list', _("Th List")),
              ('fas-icon-thumbs-down', _("Thumbs Down")),
              ('fas-icon-thumbs-down-alt', _("Thumbs Down Alt")),
              ('fas-icon-thumbs-up', _("Thumbs Up")),
              ('fas-icon-thumbs-up-alt', _("Thumbs Up Alt")),
              ('fas-icon-ticket', _("Ticket")),
              ('fas-icon-tint', _("Tint")),
              ('fas-icon-to-end', _("To End")),
              ('fas-icon-to-end-alt', _("To End Alt")),
              ('fas-icon-to-start', _("To Start")),
              ('fas-icon-to-start-alt', _("To Start Alt")),
              ('fas-icon-trash', _("Trash")),
              ('fas-icon-trello', _("Trello")),
              ('fas-icon-truck', _("Truck")),
              ('fas-icon-try', _("Try")),
              ('fas-icon-tumblr', _("Tumblr")),
              ('fas-icon-tumblr-squared', _("Tumblr Squared")),
              ('fas-icon-twitter', _("Twitter")),
              ('fas-icon-twitter-squared', _("Twitter Squared")),
              ('fas-icon-umbrella', _("Umbrella")),
              ('fas-icon-underline', _("Underline")),
              ('fas-icon-unlink', _("Unlink")),
              ('fas-icon-up', _("Up")),
              ('fas-icon-up-big', _("Up Big")),
              ('fas-icon-up-circled', _("Up Circled")),
              ('fas-icon-up-circled2', _("Up Circled2")),
              ('fas-icon-up-dir', _("Up Dir")),
              ('fas-icon-up-hand', _("Up Hand")),
              ('fas-icon-up-open', _("Up Open")),
              ('fas-icon-upload', _("Upload")),
              ('fas-icon-upload-cloud', _("Upload Cloud")),
              ('fas-icon-user', _("User")),
              ('fas-icon-user-md', _("User Md")),
              ('fas-icon-users', _("Users")),
              ('fas-icon-video', _("Video")),
              ('fas-icon-videocam', _("Videocam")),
              ('fas-icon-vimeo-squared', _("Vimeo Squared")),
              ('fas-icon-vkontakte', _("Vkontakte")),
              ('fas-icon-volume-down', _("Volume Down")),
              ('fas-icon-volume-off', _("Volume Off")),
              ('fas-icon-volume-up', _("Volume Up")),
              ('fas-icon-weibo', _("Weibo")),
              ('fas-icon-wheelchair', _("Wheelchair")),
              ('fas-icon-windows', _("Windows")),
              ('fas-icon-won', _("Won")),
              ('fas-icon-wrench', _("Wrench")),
              ('fas-icon-xing', _("Xing")),
              ('fas-icon-xing-squared', _("Xing Squared")),
              ('fas-icon-yen', _("Yen")),
              ('fas-icon-youtube', _("Youtube")),
              ('fas-icon-youtube-play', _("Youtube Play")),
              ('fas-icon-youtube-squared', _("Youtube Squared")),
              ('fas-icon-zoom-in', _("Zoom In")),
              ('fas-icon-zoom-out', _("Zoom Out"))]


class Icon(CMSPlugin):
    """
    A Icon Plugin
    """

    DEFAULT = "font-awesome"

    ICON_STYLES = [
        (DEFAULT, _('Font Awesome')),
    ]

    style = models.CharField(_('style'), choices=ICON_STYLES + get_additional_styles(),
                             default=DEFAULT, max_length=50)

    name = models.CharField(_("icon name"), choices=ICON_NAMES + get_additional_names(),
                            default=ICON_NAMES[0][0], max_length=50,
                            blank=True, null=True)

    url = models.URLField(_("link"), blank=True, null=True,
                          help_text=_("If present, clicking on icon will take user to link."))

    page_link = PageField(verbose_name=_("page"), null=True, blank=True,
                          help_text=_("If present, clicking on icon will take user to "
                                      "specified page."))

    def __unicode__(self):
        display = self.get_name_display() or u'<empty>'
        return u"%s" % display

    def clean(self):
        if self.url and self.page_link:
            raise ValidationError(
                _("You can enter a Link or a Page, but not both."))
