# -*- coding: utf-8 -*-

import os

from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import ugettext_lazy as _

from cms.models import CMSPlugin, Page
from cms.utils.compat.dj import python_2_unicode_compatible
from django.conf import settings

ICON_NAMES = getattr(settings, "CMS_ICON_NAMES", (
                     ('icons/tango/32x32/actions/address-book-new.png',
                     _("address-book-new")),
                     ('icons/tango/32x32/actions/appointment-new.png',
                     _("appointment-new")),
                     ('icons/tango/32x32/actions/bookmark-new.png',
                     _("bookmark-new")),
                     ('icons/tango/32x32/actions/contact-new.png',
                     _("contact-new")),
                     ('icons/tango/32x32/actions/document-new.png',
                     _("document-new")),
                     ('icons/tango/32x32/actions/document-open.png',
                     _("document-open")),
                     ('icons/tango/32x32/actions/document-print-preview.png',
                     _("document-print-preview")),
                     ('icons/tango/32x32/actions/document-print.png',
                     _("document-print")),
                     ('icons/tango/32x32/actions/document-properties.png',
                     _("document-properties")),
                     ('icons/tango/32x32/actions/document-save-as.png',
                     _("document-save-as")),
                     ('icons/tango/32x32/actions/document-save.png',
                     _("document-save")),
                     ('icons/tango/32x32/actions/edit-clear.png',
                     _("edit-clear")),
                     ('icons/tango/32x32/actions/edit-copy.png',
                     _("edit-copy")),
                     ('icons/tango/32x32/actions/edit-cut.png',
                     _("edit-cut")),
                     ('icons/tango/32x32/actions/edit-delete.png',
                     _("edit-delete")),
                     ('icons/tango/32x32/actions/edit-find-replace.png',
                     _("edit-find-replace")),
                     ('icons/tango/32x32/actions/edit-find.png',
                     _("edit-find")),
                     ('icons/tango/32x32/actions/edit-paste.png',
                     _("edit-paste")),
                     ('icons/tango/32x32/actions/edit-redo.png',
                     _("edit-redo")),
                     ('icons/tango/32x32/actions/edit-select-all.png',
                     _("edit-select-all")),
                     ('icons/tango/32x32/actions/edit-undo.png',
                     _("edit-undo")),
                     ('icons/tango/32x32/actions/folder-new.png',
                     _("folder-new")),
                     ('icons/tango/32x32/actions/format-indent-less.png',
                     _("format-indent-less")),
                     ('icons/tango/32x32/actions/format-indent-more.png',
                     _("format-indent-more")),
                     ('icons/tango/32x32/actions/format-justify-center.png',
                     _("format-justify-center")),
                     ('icons/tango/32x32/actions/format-justify-fill.png',
                     _("format-justify-fill")),
                     ('icons/tango/32x32/actions/format-justify-left.png',
                     _("format-justify-left")),
                     ('icons/tango/32x32/actions/format-justify-right.png',
                     _("format-justify-right")),
                     ('icons/tango/32x32/actions/format-text-bold.png',
                     _("format-text-bold")),
                     ('icons/tango/32x32/actions/format-text-italic.png',
                     _("format-text-italic")),
                     ('icons/tango/32x32/actions/format-text-strikethrough.png',
                     _("format-text-strikethrough")),
                     ('icons/tango/32x32/actions/format-text-underline.png',
                     _("format-text-underline")),
                     ('icons/tango/32x32/actions/go-bottom.png',
                     _("go-bottom")),
                     ('icons/tango/32x32/actions/go-down.png',
                     _("go-down")),
                     ('icons/tango/32x32/actions/go-first.png',
                     _("go-first")),
                     ('icons/tango/32x32/actions/go-home.png',
                     _("go-home")),
                     ('icons/tango/32x32/actions/go-jump.png',
                     _("go-jump")),
                     ('icons/tango/32x32/actions/go-last.png',
                     _("go-last")),
                     ('icons/tango/32x32/actions/go-next.png',
                     _("go-next")),
                     ('icons/tango/32x32/actions/go-previous.png',
                     _("go-previous")),
                     ('icons/tango/32x32/actions/go-top.png',
                     _("go-top")),
                     ('icons/tango/32x32/actions/go-up.png',
                     _("go-up")),
                     ('icons/tango/32x32/actions/list-add.png',
                     _("list-add")),
                     ('icons/tango/32x32/actions/list-remove.png',
                     _("list-remove")),
                     ('icons/tango/32x32/actions/mail-forward.png',
                     _("mail-forward")),
                     ('icons/tango/32x32/actions/mail-mark-junk.png',
                     _("mail-mark-junk")),
                     ('icons/tango/32x32/actions/mail-mark-not-junk.png',
                     _("mail-mark-not-junk")),
                     ('icons/tango/32x32/actions/mail-message-new.png',
                     _("mail-message-new")),
                     ('icons/tango/32x32/actions/mail-reply-all.png',
                     _("mail-reply-all")),
                     ('icons/tango/32x32/actions/mail-reply-sender.png',
                     _("mail-reply-sender")),
                     ('icons/tango/32x32/actions/mail-send-receive.png',
                     _("mail-send-receive")),
                     ('icons/tango/32x32/actions/media-eject.png',
                     _("media-eject")),
                     ('icons/tango/32x32/actions/media-playback-pause.png',
                     _("media-playback-pause")),
                     ('icons/tango/32x32/actions/media-playback-start.png',
                     _("media-playback-start")),
                     ('icons/tango/32x32/actions/media-playback-stop.png',
                     _("media-playback-stop")),
                     ('icons/tango/32x32/actions/media-record.png',
                     _("media-record")),
                     ('icons/tango/32x32/actions/media-seek-backward.png',
                     _("media-seek-backward")),
                     ('icons/tango/32x32/actions/media-seek-forward.png',
                     _("media-seek-forward")),
                     ('icons/tango/32x32/actions/media-skip-backward.png',
                     _("media-skip-backward")),
                     ('icons/tango/32x32/actions/media-skip-forward.png',
                     _("media-skip-forward")),
                     ('icons/tango/32x32/actions/process-stop.png',
                     _("process-stop")),
                     ('icons/tango/32x32/actions/system-lock-screen.png',
                     _("system-lock-screen")),
                     ('icons/tango/32x32/actions/system-log-out.png',
                     _("system-log-out")),
                     ('icons/tango/32x32/actions/system-search.png',
                     _("system-search")),
                     ('icons/tango/32x32/actions/system-shutdown.png',
                     _("system-shutdown")),
                     ('icons/tango/32x32/actions/tab-new.png',
                     _("tab-new")),
                     ('icons/tango/32x32/actions/view-fullscreen.png',
                     _("view-fullscreen")),
                     ('icons/tango/32x32/actions/view-refresh.png',
                     _("view-refresh")),
                     ('icons/tango/32x32/actions/window-new.png',
                     _("window-new")),
                     ('icons/tango/32x32/apps/accessories-calculator.png',
                     _("accessories-calculator")),
                     ('icons/tango/32x32/apps/accessories-character-map.png',
                     _("accessories-character-map")),
                     ('icons/tango/32x32/apps/accessories-text-editor.png',
                     _("accessories-text-editor")),
                     ('icons/tango/32x32/apps/help-browser.png',
                     _("help-browser")),
                     ('icons/tango/32x32/apps/internet-group-chat.png',
                     _("internet-group-chat")),
                     ('icons/tango/32x32/apps/internet-mail.png',
                     _("internet-mail")),
                     ('icons/tango/32x32/apps/internet-news-reader.png',
                     _("internet-news-reader")),
                     ('icons/tango/32x32/apps/internet-web-browser.png',
                     _("internet-web-browser")),
                     ('icons/tango/32x32/apps/office-calendar.png',
                     _("office-calendar")),
                     ('icons/tango/32x32/apps/preferences-desktop-accessibility.png',
                     _("preferences-desktop-accessibility")),
                     ('icons/tango/32x32/apps/preferences-desktop-assistive-technology.png',
                     _("preferences-desktop-assistive-technology")),
                     ('icons/tango/32x32/apps/preferences-desktop-font.png',
                     _("preferences-desktop-font")),
                     ('icons/tango/32x32/apps/preferences-desktop-keyboard-shortcuts.png',
                     _("preferences-desktop-keyboard-shortcuts")),
                     ('icons/tango/32x32/apps/preferences-desktop-locale.png',
                     _("preferences-desktop-locale")),
                     ('icons/tango/32x32/apps/preferences-desktop-multimedia.png',
                     _("preferences-desktop-multimedia")),
                     ('icons/tango/32x32/apps/preferences-desktop-remote-desktop.png',
                     _("preferences-desktop-remote-desktop")),
                     ('icons/tango/32x32/apps/preferences-desktop-screensaver.png',
                     _("preferences-desktop-screensaver")),
                     ('icons/tango/32x32/apps/preferences-desktop-theme.png',
                     _("preferences-desktop-theme")),
                     ('icons/tango/32x32/apps/preferences-desktop-wallpaper.png',
                     _("preferences-desktop-wallpaper")),
                     ('icons/tango/32x32/apps/preferences-system-network-proxy.png',
                     _("preferences-system-network-proxy")),
                     ('icons/tango/32x32/apps/preferences-system-session.png',
                     _("preferences-system-session")),
                     ('icons/tango/32x32/apps/preferences-system-windows.png',
                     _("preferences-system-windows")),
                     ('icons/tango/32x32/apps/system-file-manager.png',
                     _("system-file-manager")),
                     ('icons/tango/32x32/apps/system-installer.png',
                     _("system-installer")),
                     ('icons/tango/32x32/apps/system-software-update.png',
                     _("system-software-update")),
                     ('icons/tango/32x32/apps/system-users.png',
                     _("system-users")),
                     ('icons/tango/32x32/apps/utilities-system-monitor.png',
                     _("utilities-system-monitor")),
                     ('icons/tango/32x32/apps/utilities-terminal.png',
                     _("utilities-terminal")),
                     ('icons/tango/32x32/categories/applications-accessories.png',
                     _("applications-accessories")),
                     ('icons/tango/32x32/categories/applications-development.png',
                     _("applications-development")),
                     ('icons/tango/32x32/categories/applications-games.png',
                     _("applications-games")),
                     ('icons/tango/32x32/categories/applications-graphics.png',
                     _("applications-graphics")),
                     ('icons/tango/32x32/categories/applications-internet.png',
                     _("applications-internet")),
                     ('icons/tango/32x32/categories/applications-multimedia.png',
                     _("applications-multimedia")),
                     ('icons/tango/32x32/categories/applications-office.png',
                     _("applications-office")),
                     ('icons/tango/32x32/categories/applications-other.png',
                     _("applications-other")),
                     ('icons/tango/32x32/categories/applications-system.png',
                     _("applications-system")),
                     ('icons/tango/32x32/categories/preferences-desktop-peripherals.png',
                     _("preferences-desktop-peripherals")),
                     ('icons/tango/32x32/categories/preferences-desktop.png',
                     _("preferences-desktop")),
                     ('icons/tango/32x32/categories/preferences-system.png',
                     _("preferences-system")),
                     ('icons/tango/32x32/devices/audio-card.png',
                     _("audio-card")),
                     ('icons/tango/32x32/devices/audio-input-microphone.png',
                     _("audio-input-microphone")),
                     ('icons/tango/32x32/devices/battery.png',
                     _("battery")),
                     ('icons/tango/32x32/devices/camera-photo.png',
                     _("camera-photo")),
                     ('icons/tango/32x32/devices/camera-video.png',
                     _("camera-video")),
                     ('icons/tango/32x32/devices/computer.png',
                     _("computer")),
                     ('icons/tango/32x32/devices/drive-harddisk.png',
                     _("drive-harddisk")),
                     ('icons/tango/32x32/devices/drive-optical.png',
                     _("drive-optical")),
                     ('icons/tango/32x32/devices/drive-removable-media.png',
                     _("drive-removable-media")),
                     ('icons/tango/32x32/devices/input-gaming.png',
                     _("input-gaming")),
                     ('icons/tango/32x32/devices/input-keyboard.png',
                     _("input-keyboard")),
                     ('icons/tango/32x32/devices/input-mouse.png',
                     _("input-mouse")),
                     ('icons/tango/32x32/devices/media-flash.png',
                     _("media-flash")),
                     ('icons/tango/32x32/devices/media-floppy.png',
                     _("media-floppy")),
                     ('icons/tango/32x32/devices/media-optical.png',
                     _("media-optical")),
                     ('icons/tango/32x32/devices/multimedia-player.png',
                     _("multimedia-player")),
                     ('icons/tango/32x32/devices/network-wired.png',
                     _("network-wired")),
                     ('icons/tango/32x32/devices/network-wireless.png',
                     _("network-wireless")),
                     ('icons/tango/32x32/devices/printer.png',
                     _("printer")),
                     ('icons/tango/32x32/devices/video-display.png',
                     _("video-display")),
                     ('icons/tango/32x32/emblems/emblem-favorite.png',
                     _("emblem-favorite")),
                     ('icons/tango/32x32/emblems/emblem-important.png',
                     _("emblem-important")),
                     ('icons/tango/32x32/emblems/emblem-photos.png',
                     _("emblem-photos")),
                     ('icons/tango/32x32/emblems/emblem-readonly.png',
                     _("emblem-readonly")),
                     ('icons/tango/32x32/emblems/emblem-symbolic-link.png',
                     _("emblem-symbolic-link")),
                     ('icons/tango/32x32/emblems/emblem-system.png',
                     _("emblem-system")),
                     ('icons/tango/32x32/emblems/emblem-unreadable.png',
                     _("emblem-unreadable")),
                     ('icons/tango/32x32/emotes/face-angel.png',
                     _("face-angel")),
                     ('icons/tango/32x32/emotes/face-crying.png',
                     _("face-crying")),
                     ('icons/tango/32x32/emotes/face-devilish.png',
                     _("face-devilish")),
                     ('icons/tango/32x32/emotes/face-glasses.png',
                     _("face-glasses")),
                     ('icons/tango/32x32/emotes/face-grin.png',
                     _("face-grin")),
                     ('icons/tango/32x32/emotes/face-kiss.png',
                     _("face-kiss")),
                     ('icons/tango/32x32/emotes/face-monkey.png',
                     _("face-monkey")),
                     ('icons/tango/32x32/emotes/face-plain.png',
                     _("face-plain")),
                     ('icons/tango/32x32/emotes/face-sad.png',
                     _("face-sad")),
                     ('icons/tango/32x32/emotes/face-smile-big.png',
                     _("face-smile-big")),
                     ('icons/tango/32x32/emotes/face-smile.png',
                     _("face-smile")),
                     ('icons/tango/32x32/emotes/face-surprise.png',
                     _("face-surprise")),
                     ('icons/tango/32x32/emotes/face-wink.png',
                     _("face-wink")),
                     ('icons/tango/32x32/mimetypes/application-certificate.png',
                     _("application-certificate")),
                     ('icons/tango/32x32/mimetypes/application-x-executable.png',
                     _("application-x-executable")),
                     ('icons/tango/32x32/mimetypes/audio-x-generic.png',
                     _("audio-x-generic")),
                     ('icons/tango/32x32/mimetypes/font-x-generic.png',
                     _("font-x-generic")),
                     ('icons/tango/32x32/mimetypes/image-x-generic.png',
                     _("image-x-generic")),
                     ('icons/tango/32x32/mimetypes/package-x-generic.png',
                     _("package-x-generic")),
                     ('icons/tango/32x32/mimetypes/text-html.png',
                     _("text-html")),
                     ('icons/tango/32x32/mimetypes/text-x-generic-template.png',
                     _("text-x-generic-template")),
                     ('icons/tango/32x32/mimetypes/text-x-generic.png',
                     _("text-x-generic")),
                     ('icons/tango/32x32/mimetypes/text-x-script.png',
                     _("text-x-script")),
                     ('icons/tango/32x32/mimetypes/video-x-generic.png',
                     _("video-x-generic")),
                     ('icons/tango/32x32/mimetypes/x-office-address-book.png',
                     _("x-office-address-book")),
                     ('icons/tango/32x32/mimetypes/x-office-calendar.png',
                     _("x-office-calendar")),
                     ('icons/tango/32x32/mimetypes/x-office-document-template.png',
                     _("x-office-document-template")),
                     ('icons/tango/32x32/mimetypes/x-office-document.png',
                     _("x-office-document")),
                     ('icons/tango/32x32/mimetypes/x-office-drawing-template.png',
                     _("x-office-drawing-template")),
                     ('icons/tango/32x32/mimetypes/x-office-drawing.png',
                     _("x-office-drawing")),
                     ('icons/tango/32x32/mimetypes/x-office-presentation-template.png',
                     _("x-office-presentation-template")),
                     ('icons/tango/32x32/mimetypes/x-office-presentation.png',
                     _("x-office-presentation")),
                     ('icons/tango/32x32/mimetypes/x-office-spreadsheet-template.png',
                     _("x-office-spreadsheet-template")),
                     ('icons/tango/32x32/mimetypes/x-office-spreadsheet.png',
                     _("x-office-spreadsheet")),
                     ('icons/tango/32x32/places/folder-remote.png',
                     _("folder-remote")),
                     ('icons/tango/32x32/places/folder-saved-search.png',
                     _("folder-saved-search")),
                     ('icons/tango/32x32/places/folder.png',
                     _("folder")),
                     ('icons/tango/32x32/places/network-server.png',
                     _("network-server")),
                     ('icons/tango/32x32/places/network-workgroup.png',
                     _("network-workgroup")),
                     ('icons/tango/32x32/places/start-here.png',
                     _("start-here")),
                     ('icons/tango/32x32/places/user-desktop.png',
                     _("user-desktop")),
                     ('icons/tango/32x32/places/user-home.png',
                     _("user-home")),
                     ('icons/tango/32x32/places/user-trash.png',
                     _("user-trash")),
                     ('icons/tango/32x32/status/audio-volume-high.png',
                     _("audio-volume-high")),
                     ('icons/tango/32x32/status/audio-volume-low.png',
                     _("audio-volume-low")),
                     ('icons/tango/32x32/status/audio-volume-medium.png',
                     _("audio-volume-medium")),
                     ('icons/tango/32x32/status/audio-volume-muted.png',
                     _("audio-volume-muted")),
                     ('icons/tango/32x32/status/battery-caution.png',
                     _("battery-caution")),
                     ('icons/tango/32x32/status/dialog-error.png',
                     _("dialog-error")),
                     ('icons/tango/32x32/status/dialog-information.png',
                     _("dialog-information")),
                     ('icons/tango/32x32/status/dialog-warning.png',
                     _("dialog-warning")),
                     ('icons/tango/32x32/status/folder-drag-accept.png',
                     _("folder-drag-accept")),
                     ('icons/tango/32x32/status/folder-open.png',
                     _("folder-open")),
                     ('icons/tango/32x32/status/folder-visiting.png',
                     _("folder-visiting")),
                     ('icons/tango/32x32/status/image-loading.png',
                     _("image-loading")),
                     ('icons/tango/32x32/status/image-missing.png',
                     _("image-missing")),
                     ('icons/tango/32x32/status/mail-attachment.png',
                     _("mail-attachment")),
                     ('icons/tango/32x32/status/network-error.png',
                     _("network-error")),
                     ('icons/tango/32x32/status/network-idle.png',
                     _("network-idle")),
                     ('icons/tango/32x32/status/network-offline.png',
                     _("network-offline")),
                     ('icons/tango/32x32/status/network-receive.png',
                     _("network-receive")),
                     ('icons/tango/32x32/status/network-transmit-receive.png',
                     _("network-transmit-receive")),
                     ('icons/tango/32x32/status/network-transmit.png',
                     _("network-transmit")),
                     ('icons/tango/32x32/status/network-wireless-encrypted.png',
                     _("network-wireless-encrypted")),
                     ('icons/tango/32x32/status/printer-error.png',
                     _("printer-error")),
                     ('icons/tango/32x32/status/software-update-available.png',
                     _("software-update-available")),
                     ('icons/tango/32x32/status/software-update-urgent.png',
                     _("software-update-urgent")),
                     ('icons/tango/32x32/status/user-trash-full.png',
                     _("user-trash-full")),
                     ('icons/tango/32x32/status/weather-clear-night.png',
                     _("weather-clear-night")),
                     ('icons/tango/32x32/status/weather-clear.png',
                     _("weather-clear")),
                     ('icons/tango/32x32/status/weather-few-clouds-night.png',
                     _("weather-few-clouds-night")),
                     ('icons/tango/32x32/status/weather-few-clouds.png',
                     _("weather-few-clouds")),
                     ('icons/tango/32x32/status/weather-overcast.png',
                     _("weather-overcast")),
                     ('icons/tango/32x32/status/weather-severe-alert.png',
                     _("weather-severe-alert")),
                     ('icons/tango/32x32/status/weather-showers-scattered.png',
                     _("weather-showers-scattered")),
                     ('icons/tango/32x32/status/weather-showers.png',
                     _("weather-showers")),
                     ('icons/tango/32x32/status/weather-snow.png',
                     _("weather-snow")),
                     ('icons/tango/32x32/status/weather-storm.png',
                     _("weather-storm")),
                     ))


@python_2_unicode_compatible
class Icon(CMSPlugin):
    """
    A Icon Plugin
    """
    LEFT = "left"
    RIGHT = "right"
    CENTER = "center"
    FLOAT_CHOICES = ((LEFT, _("left")),
                     (RIGHT, _("right")),
                     (CENTER, _("center")),
                     )

    name = models.CharField(_("icon name"), choices=ICON_NAMES,
                            default=ICON_NAMES[0][0], max_length=150,
                            blank=True, null=True)

    url = models.CharField(
        _("link"), max_length=255, blank=True, null=True,
        help_text=_("If present, clicking on icon will take user to link."))

    page_link = models.ForeignKey(
        Page, verbose_name=_("page"), null=True,
        limit_choices_to={'publisher_is_draft': True}, blank=True,
        help_text=_("If present, clicking on icon will take user to "
                    "specified page."))

    alt = models.CharField(
        _("alternate text"), max_length=255, blank=True, null=True,
        help_text=_("Specifies an alternate text for an icon, if the icon"
                    "cannot be displayed.<br />Is also used by search engines"
                    "to classify the icon."))

    float = models.CharField(
        _("side"), max_length=10, blank=True, null=True, choices=FLOAT_CHOICES,
        help_text=_("Move icon left, right or center."))

    def __str__(self):
        if self.alt:
            return self.alt[:40]
        elif self.name:
            # added if, because it raised attribute error when file wasn't
            # defined.
            try:
                return u"%s" % os.path.basename(self.name)
            except:
                pass
        return "<empty>"

    def clean(self):
        if self.url and self.page_link:
            raise ValidationError(
                _("You can enter a Link or a Page, but not both."))
